
baseURL = "https://airflowsummit.org/"
title = "Airflow Summit 2025"
description = "Airflow Summit is the premier conference for the worldwide community of developers and users of Apache Airflow."
enableRobotsTXT = true
RemovePathAccents = true
DefaultContentLanguage = "en"

theme = "airflowsummit"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"


############################## navigation ###############################
[menu]

  [[menu.main]]
    name = "About"
    URL = "/about"
    weight = 1

  [[menu.main]]
  identifier = "about-AS"
  name = "Attend"
  URL = "/attend"
  weight = 2

  [[menu.main]]
    identifier = "scholarships"
    name = "Venue + Travel"
    url = "/venue"
    parent = "about-AS"
    weight = 2

  [[menu.main]]
    identifier = "scholarships1"
    name = "Convince your boss"
    url = "/convince-your-boss"
    parent = "about-AS"
    weight = 3

  [[menu.main]]
    identifier = "scholarships2"
    name = "Visa letter request"
    url = "/visa-letter-request"
    parent = "about-AS"
    weight = 3

  [[menu.main]]
    identifier = "scholarships3"
    name = "DEI"
    url = "/dei"
    parent = "about-AS"
    weight = 4

  [[menu.main]]
    identifier = "scholarships3"
    name = "Code of conduct"
    url = "/coc"
    parent = "about-AS"
    weight = 4

  [[menu.main]]
    name = "Sponsor"
    hrefTargetBlank = true
    URL = "/partner-with-us"
    weight = 3

  [[menu.main]]
    identifier="program"
    name = "Program"
    URL = "/sessions/2024"
    weight = 5

  [[menu.main]]
    identifier="cfp"
    name = "Call for Papers 2025"
    parent="program"
    URL = "/blog/cfp"
    weight = 1

  [[menu.main]]
    identifier="hapennings"
    name = "Happenings"
    parent="program"
    URL = "/happenings"
    weight = 2

  [[menu.main]]
    name = "Session archive"
    URL = "/sessions/"
    parent="program"
    weight = 3

  [[menu.main]]
    name = "Speaker archive"
    URL = "/speakers/"
    parent="program"
    weight = 4

  #[[menu.main]]
  #  name = "Venue"
  #  URL = "/venue"
  #  weight = 6

  #[[menu.main]]
  #  name = "Jobs"
  #  URL = "/jobs"
  #  weight = 7

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 8


# Everything below this are Site Params

[params]
description = "Airflow Summit is the premier conference for the worldwide community of developers and users of Apache Airflow."
logo = "/images/logo-pinwheel.svg"
home = "Home"
# privacy_policy = "/privacy"
google_analytics_4 = "G-DQ3SEJY0LP"
google_ads = "AW-10857785820"

# First one is picked as the Twitter card image if not set on page.
images = ["/images/card-as-2025.jpg"]
start_date = "2025-10-07T09:00-05:00"
end_date = "2025-10-09T17:00-05:00" 

[params.hero]
text = "October 7 - 9, 2025."

# [params.hero.cta1]
# text = "Submit to our CFP"
# link = "https://sessionize.com/airflow-summit-2024/"

[params.hero.cta2]
text = "2024 Sessions"
link = "/sessions/2024"

# Navigation button
[params.navigation_button]
enable = true
label = "Register"
link = "/tickets"


[params.links]
[[params.links.media]]
    name = "Email us"
    url = "mailto:info@airflowsummit.org"
    icon = "fa fa-envelope"
[[params.links.media]]
    name = "Follow us on Twitter"
    url = "https://twitter.com/airflowsummit/"
    icon = "fab fa-twitter"
[[params.links.media]]
    name = "Check us on LinkedIn"
    url = "https://www.linkedin.com/company/airflow-summit"
    icon = "fab fa-linkedin-in"
[[params.links.media]]
    name = "Watch us on YouTube"
    url = "https://www.youtube.com/channel/UCSXwxpWZQ7XZ1WL3wqevChA/"
    icon = "fab fa-youtube"
[[params.links.media]]
    name = "Check us on Instagram"
    url = "https://www.instagram.com/airflowsummit/"
    icon = "fab fa-instagram"

[[params.links.footer]]
    name = "Prospectus"
    url = "/docs/airflowsummit2025-prospectus-v1.1.pdf"
    target="_blank"
[[params.links.footer]]
    name = "Session archive"
    url = "/sessions"
[[params.links.footer]]
    name = "Speaker archive"
    url = "/speakers/archive/"
[[params.links.footer]]
    name = "Organizers"
    url = "/team"
[[params.links.footer]]
    name = "Code of Conduct"
    url = "/coc"
[[params.links.footer]]
    name = "Accessibility"
    url = "/accessibility"
[[params.links.footer]] 
    name = "Privacy Policy"
    url = "/privacy"
[[params.links.footer]]
    name = "Testimonials"
    url = "/testimonials"


[permalinks]
tags = "/blog/tags/:slug/"
posts = "/:year/:month/:title/"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap.min.css"

[[params.plugins.css]]
link = "/plugins/bootstrap-table.min.css"

[[params.plugins.css]]
link = "/plugins/fontawesome.css"

# JS Plugins
[[params.plugins.js]]
link="/plugins/jquery.min.js"

[[params.plugins.js]]
link="/plugins/bootstrap.bundle.min.js"

[[params.plugins.js]]
link="/plugins/bootstrap-table.min.js"

